#!/usr/bin/env bash
set -euo pipefail

# Refresh README TOC using ekalinin/github-markdown-toc.
# Exits non-zero only when it actually changes the file.

TARGET_FILE="${1:-README.md}"

tmp_script="$(mktemp)"
tmp_work="$(mktemp)"
tmp_clean="$(mktemp)"
trap 'rm -f "$tmp_script" "$tmp_work" "$tmp_clean"' EXIT

curl -fsSL https://raw.githubusercontent.com/ekalinin/github-markdown-toc/master/gh-md-toc > "$tmp_script"
chmod +x "$tmp_script"

cp "$TARGET_FILE" "$tmp_work"
"$tmp_script" --no-backup "$tmp_work" >/dev/null 2>&1

# Drop metadata comments the tool inserts.
sed -e '/<!-- Added by: /d' \
  -e '\|<!-- Auto generated by https://github.com/ekalinin/github-markdown-toc -->|d' \
  -e '\|<!-- Created by https://github.com/ekalinin/github-markdown-toc -->|d' \
  "$tmp_work" > "$tmp_clean"
mv "$tmp_clean" "$tmp_work"

if cmp -s "$TARGET_FILE" "$tmp_work"; then
  exit 0
fi

mv "$tmp_work" "$TARGET_FILE"
exit 1
