---
# used for publishing documentation on push to main or published release
name: publish docs

on:
  push:
    branches:
      - main
  release:
    types:
      - published

jobs:
  build:
    # only build and deploy docs if the actor is not dependabot
    if: ${{ github.actor != 'dependabot[bot]' }}
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - name: Fetch tags
        run: git fetch --all --tags
      - uses: actions/setup-python@v6
        with:
          python-version: "3.11"
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v8.2.0
        with:
          # docs publish runs are one-off; skip cache upload
          enable-cache: false
      - name: Install environment
        run: uv sync --no-default-groups --group docs
      - name: Build documentation
        run: |
          mkdir pages
          touch pages/.nojekyll
          cd docs
          uv run --frozen --no-default-groups --group docs \
            sphinx-multiversion src build
          # remove any doctrees dirs which aren't needed for publishing
          find ./build -type d -name '.doctrees' -exec rm -rf {} +
          cp -r build/* ../pages/
      - name: Add index redirector to latest docs
        run: |
          cp docs/redirector.html pages/index.html
      - name: Add media folder to latest docs
        run: |
          cp -r docs/src/media pages/media
      - name: Deploy documentation
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: pages
          folder: pages
